version: '3'

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - ${POSTGRES_DATA_DIRECTORY}:/var/lib/postgresql/data

  php:
    build: .
    env_file:
      - .env
    volumes:
      - ./src:/var/www/html
    ports:
      - "8000:80"
    depends_on:
      - postgres
